<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/02/25 22:10:54

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=udes_testpractico',
  'username' => 'udes',
  'password' => 'udes',
  'name' => 'doctrine',
)),);
